FROM projectatomic/atomicapp:0.1.3

MAINTAINER Jason Brooks <jbrooks@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.2
LABEL io.projectatomic.nulecule.providers = "docker"

ADD /Nulecule /Dockerfile /answers.conf /application-entity/
ADD /artifacts /application-entity/artifacts
